# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_measure_parameters_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_measure_params_dialog(object):
    def setupUi(self, edit_measure_params_dialog):
        edit_measure_params_dialog.setObjectName("edit_measure_params_dialog")
        edit_measure_params_dialog.resize(578, 454)
        font = QtGui.QFont()
        font.setPointSize(10)
        edit_measure_params_dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(edit_measure_params_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(edit_measure_params_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.device_creator_edit = QtWidgets.QLineEdit(edit_measure_params_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.device_creator_edit.sizePolicy().hasHeightForWidth())
        self.device_creator_edit.setSizePolicy(sizePolicy)
        self.device_creator_edit.setObjectName("device_creator_edit")
        self.gridLayout.addWidget(self.device_creator_edit, 1, 1, 1, 1)
        self.system_combobox = QtWidgets.QComboBox(edit_measure_params_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.system_combobox.sizePolicy().hasHeightForWidth())
        self.system_combobox.setSizePolicy(sizePolicy)
        self.system_combobox.setObjectName("system_combobox")
        self.system_combobox.addItem("")
        self.system_combobox.addItem("")
        self.system_combobox.addItem("")
        self.gridLayout.addWidget(self.system_combobox, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(edit_measure_params_dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(edit_measure_params_dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(edit_measure_params_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(edit_measure_params_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.device_name_edit = QtWidgets.QLineEdit(edit_measure_params_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.device_name_edit.sizePolicy().hasHeightForWidth())
        self.device_name_edit.setSizePolicy(sizePolicy)
        self.device_name_edit.setObjectName("device_name_edit")
        self.gridLayout.addWidget(self.device_name_edit, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(edit_measure_params_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(edit_measure_params_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.owner_edit = QtWidgets.QLineEdit(edit_measure_params_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.owner_edit.sizePolicy().hasHeightForWidth())
        self.owner_edit.setSizePolicy(sizePolicy)
        self.owner_edit.setObjectName("owner_edit")
        self.gridLayout.addWidget(self.owner_edit, 3, 2, 1, 1)
        self.user_name_edit = QtWidgets.QLineEdit(edit_measure_params_dialog)
        self.user_name_edit.setObjectName("user_name_edit")
        self.gridLayout.addWidget(self.user_name_edit, 3, 0, 1, 1)
        self.date_edit = QtWidgets.QDateTimeEdit(edit_measure_params_dialog)
        self.date_edit.setObjectName("date_edit")
        self.gridLayout.addWidget(self.date_edit, 5, 0, 1, 1)
        self.serial_number_edit = QtWidgets.QLineEdit(edit_measure_params_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_number_edit.sizePolicy().hasHeightForWidth())
        self.serial_number_edit.setSizePolicy(sizePolicy)
        self.serial_number_edit.setObjectName("serial_number_edit")
        self.gridLayout.addWidget(self.serial_number_edit, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(edit_measure_params_dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 1, 1, 2)
        self.comment_edit = QtWidgets.QLineEdit(edit_measure_params_dialog)
        self.comment_edit.setObjectName("comment_edit")
        self.gridLayout.addWidget(self.comment_edit, 5, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.widget_2 = QtWidgets.QWidget(edit_measure_params_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.marks_widget_layout = QtWidgets.QVBoxLayout()
        self.marks_widget_layout.setObjectName("marks_widget_layout")
        self.horizontalLayout.addLayout(self.marks_widget_layout)
        self.verticalLayout.addWidget(self.widget_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.default_button = QtWidgets.QPushButton(edit_measure_params_dialog)
        self.default_button.setEnabled(False)
        self.default_button.setDefault(True)
        self.default_button.setObjectName("default_button")
        self.horizontalLayout_2.addWidget(self.default_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.accept_button = QtWidgets.QPushButton(edit_measure_params_dialog)
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout_2.addWidget(self.accept_button)
        self.reject_button = QtWidgets.QPushButton(edit_measure_params_dialog)
        self.reject_button.setObjectName("reject_button")
        self.horizontalLayout_2.addWidget(self.reject_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(edit_measure_params_dialog)
        QtCore.QMetaObject.connectSlotsByName(edit_measure_params_dialog)
        edit_measure_params_dialog.setTabOrder(self.device_name_edit, self.device_creator_edit)
        edit_measure_params_dialog.setTabOrder(self.device_creator_edit, self.system_combobox)
        edit_measure_params_dialog.setTabOrder(self.system_combobox, self.user_name_edit)
        edit_measure_params_dialog.setTabOrder(self.user_name_edit, self.serial_number_edit)
        edit_measure_params_dialog.setTabOrder(self.serial_number_edit, self.owner_edit)
        edit_measure_params_dialog.setTabOrder(self.owner_edit, self.date_edit)
        edit_measure_params_dialog.setTabOrder(self.date_edit, self.comment_edit)
        edit_measure_params_dialog.setTabOrder(self.comment_edit, self.accept_button)
        edit_measure_params_dialog.setTabOrder(self.accept_button, self.reject_button)
        edit_measure_params_dialog.setTabOrder(self.reject_button, self.default_button)

    def retranslateUi(self, edit_measure_params_dialog):
        _translate = QtCore.QCoreApplication.translate
        edit_measure_params_dialog.setWindowTitle(_translate("edit_measure_params_dialog", "Изменение параметров поверки"))
        self.label_5.setText(_translate("edit_measure_params_dialog", "Изготовитель"))
        self.system_combobox.setItemText(0, _translate("edit_measure_params_dialog", "Магнитоэлектрическая"))
        self.system_combobox.setItemText(1, _translate("edit_measure_params_dialog", "Электродинамическая"))
        self.system_combobox.setItemText(2, _translate("edit_measure_params_dialog", "Электромагнитная"))
        self.label_6.setText(_translate("edit_measure_params_dialog", "Дата поверки"))
        self.label.setText(_translate("edit_measure_params_dialog", "Поверитель"))
        self.label_7.setText(_translate("edit_measure_params_dialog", "Заводской номер"))
        self.label_2.setText(_translate("edit_measure_params_dialog", "Система"))
        self.label_3.setText(_translate("edit_measure_params_dialog", "Организация-владелец"))
        self.label_4.setText(_translate("edit_measure_params_dialog", "Наименование"))
        self.date_edit.setDisplayFormat(_translate("edit_measure_params_dialog", "dd.MM.yyyy"))
        self.label_8.setText(_translate("edit_measure_params_dialog", "Комментарий"))
        self.default_button.setText(_translate("edit_measure_params_dialog", "default"))
        self.accept_button.setText(_translate("edit_measure_params_dialog", "Сохранить"))
        self.reject_button.setText(_translate("edit_measure_params_dialog", "Отмена"))
