# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_case_params_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_case_params_dialog(object):
    def setupUi(self, edit_case_params_dialog):
        edit_case_params_dialog.setObjectName("edit_case_params_dialog")
        edit_case_params_dialog.resize(303, 146)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(edit_case_params_dialog.sizePolicy().hasHeightForWidth())
        edit_case_params_dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        edit_case_params_dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(edit_case_params_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(edit_case_params_dialog)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(edit_case_params_dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(edit_case_params_dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(edit_case_params_dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 1, 1)
        self.minimal_discrete_edit = QEditDoubleClick(edit_case_params_dialog)
        self.minimal_discrete_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.minimal_discrete_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minimal_discrete_edit.setFont(font)
        self.minimal_discrete_edit.setObjectName("minimal_discrete_edit")
        self.gridLayout_4.addWidget(self.minimal_discrete_edit, 4, 0, 1, 1)
        self.device_class_spinbox = QtWidgets.QDoubleSpinBox(edit_case_params_dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.device_class_spinbox.setFont(font)
        self.device_class_spinbox.setDecimals(4)
        self.device_class_spinbox.setMinimum(0.0001)
        self.device_class_spinbox.setMaximum(10.0)
        self.device_class_spinbox.setSingleStep(0.05)
        self.device_class_spinbox.setProperty("value", 0.05)
        self.device_class_spinbox.setObjectName("device_class_spinbox")
        self.gridLayout_4.addWidget(self.device_class_spinbox, 4, 1, 1, 1)
        self.signal_type_combobox = QtWidgets.QComboBox(edit_case_params_dialog)
        self.signal_type_combobox.setObjectName("signal_type_combobox")
        self.signal_type_combobox.addItem("")
        self.signal_type_combobox.addItem("")
        self.signal_type_combobox.addItem("")
        self.signal_type_combobox.addItem("")
        self.gridLayout_4.addWidget(self.signal_type_combobox, 1, 1, 1, 1)
        self.limit_edit = QEditDoubleClick(edit_case_params_dialog)
        self.limit_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.limit_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.limit_edit.setFont(font)
        self.limit_edit.setObjectName("limit_edit")
        self.gridLayout_4.addWidget(self.limit_edit, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.default_button = QtWidgets.QPushButton(edit_case_params_dialog)
        self.default_button.setEnabled(False)
        self.default_button.setDefault(True)
        self.default_button.setObjectName("default_button")
        self.horizontalLayout_2.addWidget(self.default_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.accept_button = QtWidgets.QPushButton(edit_case_params_dialog)
        self.accept_button.setAutoDefault(False)
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout_2.addWidget(self.accept_button)
        self.reject_button = QtWidgets.QPushButton(edit_case_params_dialog)
        self.reject_button.setAutoDefault(False)
        self.reject_button.setObjectName("reject_button")
        self.horizontalLayout_2.addWidget(self.reject_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(edit_case_params_dialog)
        QtCore.QMetaObject.connectSlotsByName(edit_case_params_dialog)
        edit_case_params_dialog.setTabOrder(self.limit_edit, self.signal_type_combobox)
        edit_case_params_dialog.setTabOrder(self.signal_type_combobox, self.minimal_discrete_edit)
        edit_case_params_dialog.setTabOrder(self.minimal_discrete_edit, self.device_class_spinbox)
        edit_case_params_dialog.setTabOrder(self.device_class_spinbox, self.accept_button)
        edit_case_params_dialog.setTabOrder(self.accept_button, self.reject_button)
        edit_case_params_dialog.setTabOrder(self.reject_button, self.default_button)

    def retranslateUi(self, edit_case_params_dialog):
        _translate = QtCore.QCoreApplication.translate
        edit_case_params_dialog.setWindowTitle(_translate("edit_case_params_dialog", "Параметры измерения"))
        self.label.setText(_translate("edit_case_params_dialog", "Предел"))
        self.label_3.setText(_translate("edit_case_params_dialog", "Класс прибора"))
        self.label_2.setText(_translate("edit_case_params_dialog", "Минимальный дискрет"))
        self.label_4.setText(_translate("edit_case_params_dialog", "Тип сигнала"))
        self.minimal_discrete_edit.setText(_translate("edit_case_params_dialog", "0"))
        self.signal_type_combobox.setItemText(0, _translate("edit_case_params_dialog", "I~"))
        self.signal_type_combobox.setItemText(1, _translate("edit_case_params_dialog", "U~"))
        self.signal_type_combobox.setItemText(2, _translate("edit_case_params_dialog", "I="))
        self.signal_type_combobox.setItemText(3, _translate("edit_case_params_dialog", "U="))
        self.limit_edit.setText(_translate("edit_case_params_dialog", "0"))
        self.default_button.setText(_translate("edit_case_params_dialog", "default"))
        self.accept_button.setText(_translate("edit_case_params_dialog", "Принять"))
        self.reject_button.setText(_translate("edit_case_params_dialog", "Отмена"))
from custom_widgets.CustomLineEdit import QEditDoubleClick
