# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/edit_case_params_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(261, 146)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 1, 1)
        self.minimal_discrete_edit = QEditDoubleClick(Dialog)
        self.minimal_discrete_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.minimal_discrete_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minimal_discrete_edit.setFont(font)
        self.minimal_discrete_edit.setObjectName("minimal_discrete_edit")
        self.gridLayout_4.addWidget(self.minimal_discrete_edit, 4, 0, 1, 1)
        self.device_class_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.device_class_spinbox.setFont(font)
        self.device_class_spinbox.setDecimals(4)
        self.device_class_spinbox.setMinimum(0.0001)
        self.device_class_spinbox.setMaximum(10.0)
        self.device_class_spinbox.setSingleStep(0.05)
        self.device_class_spinbox.setProperty("value", 0.05)
        self.device_class_spinbox.setObjectName("device_class_spinbox")
        self.gridLayout_4.addWidget(self.device_class_spinbox, 4, 1, 1, 1)
        self.signal_type_combobox = QtWidgets.QComboBox(Dialog)
        self.signal_type_combobox.setObjectName("signal_type_combobox")
        self.signal_type_combobox.addItem("")
        self.signal_type_combobox.addItem("")
        self.signal_type_combobox.addItem("")
        self.signal_type_combobox.addItem("")
        self.gridLayout_4.addWidget(self.signal_type_combobox, 1, 1, 1, 1)
        self.limit_edit = QEditDoubleClick(Dialog)
        self.limit_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.limit_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.limit_edit.setFont(font)
        self.limit_edit.setObjectName("limit_edit")
        self.gridLayout_4.addWidget(self.limit_edit, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.default_button = QtWidgets.QPushButton(Dialog)
        self.default_button.setEnabled(False)
        self.default_button.setDefault(True)
        self.default_button.setObjectName("default_button")
        self.horizontalLayout_2.addWidget(self.default_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.accept_button = QtWidgets.QPushButton(Dialog)
        self.accept_button.setAutoDefault(False)
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout_2.addWidget(self.accept_button)
        self.reject_button = QtWidgets.QPushButton(Dialog)
        self.reject_button.setAutoDefault(False)
        self.reject_button.setObjectName("reject_button")
        self.horizontalLayout_2.addWidget(self.reject_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.accept_button, self.reject_button)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Параметры измерения"))
        self.label.setText(_translate("Dialog", "Предел"))
        self.label_3.setText(_translate("Dialog", "Класс прибора"))
        self.label_2.setText(_translate("Dialog", "Минимальный дискрет"))
        self.label_4.setText(_translate("Dialog", "Тип сигнала"))
        self.minimal_discrete_edit.setText(_translate("Dialog", "0"))
        self.signal_type_combobox.setItemText(0, _translate("Dialog", "I~"))
        self.signal_type_combobox.setItemText(1, _translate("Dialog", "U~"))
        self.signal_type_combobox.setItemText(2, _translate("Dialog", "I="))
        self.signal_type_combobox.setItemText(3, _translate("Dialog", "U="))
        self.limit_edit.setText(_translate("Dialog", "0"))
        self.default_button.setText(_translate("Dialog", "default"))
        self.accept_button.setText(_translate("Dialog", "Принять"))
        self.reject_button.setText(_translate("Dialog", "Отмена"))
from custom_widgets.CustomLineEdit import QEditDoubleClick
