# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/edit_template_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(633, 538)
        font = QtGui.QFont()
        font.setPointSize(13)
        Dialog.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setMidLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.info_layout = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_layout.sizePolicy().hasHeightForWidth())
        self.info_layout.setSizePolicy(sizePolicy)
        self.info_layout.setObjectName("info_layout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.info_layout)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.info_layout)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.describe_edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.describe_edit.setObjectName("describe_edit")
        self.gridLayout_3.addWidget(self.describe_edit, 1, 0, 1, 1)
        self.organisation_edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.organisation_edit.setText("")
        self.organisation_edit.setReadOnly(False)
        self.organisation_edit.setObjectName("organisation_edit")
        self.gridLayout_3.addWidget(self.organisation_edit, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 3, 1, 1)
        self.calibrator_edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.calibrator_edit.setReadOnly(True)
        self.calibrator_edit.setObjectName("calibrator_edit")
        self.gridLayout_3.addWidget(self.calibrator_edit, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.info_layout)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.name_edit = QtWidgets.QLineEdit(self.groupBox)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout.addWidget(self.name_edit, 1, 0, 1, 1)
        self.creator_edit = QtWidgets.QLineEdit(self.groupBox)
        self.creator_edit.setObjectName("creator_edit")
        self.gridLayout.addWidget(self.creator_edit, 1, 1, 1, 1)
        self.signal_type_combobox = QtWidgets.QComboBox(self.groupBox)
        self.signal_type_combobox.setObjectName("signal_type_combobox")
        self.signal_type_combobox.addItem("")
        self.signal_type_combobox.addItem("")
        self.signal_type_combobox.addItem("")
        self.signal_type_combobox.addItem("")
        self.gridLayout.addWidget(self.signal_type_combobox, 1, 2, 1, 1)
        self.system_combobox = QtWidgets.QComboBox(self.groupBox)
        self.system_combobox.setObjectName("system_combobox")
        self.system_combobox.addItem("")
        self.system_combobox.addItem("")
        self.system_combobox.addItem("")
        self.gridLayout.addWidget(self.system_combobox, 1, 3, 1, 1)
        self.class_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.class_spinbox.setDecimals(4)
        self.class_spinbox.setMinimum(0.001)
        self.class_spinbox.setMaximum(10.0)
        self.class_spinbox.setSingleStep(0.05)
        self.class_spinbox.setProperty("value", 1.5)
        self.class_spinbox.setObjectName("class_spinbox")
        self.gridLayout.addWidget(self.class_spinbox, 1, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.points_table = QtWidgets.QTableWidget(self.tab)
        self.points_table.setObjectName("points_table")
        self.points_table.setColumnCount(0)
        self.points_table.setRowCount(0)
        self.gridLayout_5.addWidget(self.points_table, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.add_point_button = QtWidgets.QPushButton(self.tab)
        self.add_point_button.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add_point_button.setFont(font)
        self.add_point_button.setObjectName("add_point_button")
        self.verticalLayout_4.addWidget(self.add_point_button)
        self.remove_point_button = QtWidgets.QPushButton(self.tab)
        self.remove_point_button.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.remove_point_button.setFont(font)
        self.remove_point_button.setObjectName("remove_point_button")
        self.verticalLayout_4.addWidget(self.remove_point_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.marks_table = QtWidgets.QTableWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.marks_table.sizePolicy().hasHeightForWidth())
        self.marks_table.setSizePolicy(sizePolicy)
        self.marks_table.setObjectName("marks_table")
        self.marks_table.setColumnCount(3)
        self.marks_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.marks_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.marks_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.marks_table.setHorizontalHeaderItem(2, item)
        self.gridLayout_6.addWidget(self.marks_table, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.add_mark_button = QtWidgets.QPushButton(self.tab_2)
        self.add_mark_button.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add_mark_button.setFont(font)
        self.add_mark_button.setObjectName("add_mark_button")
        self.verticalLayout_3.addWidget(self.add_mark_button)
        self.remove_mark_button = QtWidgets.QPushButton(self.tab_2)
        self.remove_mark_button.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.remove_mark_button.setFont(font)
        self.remove_mark_button.setObjectName("remove_mark_button")
        self.verticalLayout_3.addWidget(self.remove_mark_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.accept_button = QtWidgets.QPushButton(Dialog)
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout_2.addWidget(self.accept_button)
        self.reject_button = QtWidgets.QPushButton(Dialog)
        self.reject_button.setObjectName("reject_button")
        self.horizontalLayout_2.addWidget(self.reject_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Редактирование шаблона"))
        self.groupBox_3.setTitle(_translate("Dialog", "Общая информация"))
        self.label_13.setText(_translate("Dialog", "Организация-поверитель"))
        self.label_6.setText(_translate("Dialog", "Описание шаблона"))
        self.label_7.setText(_translate("Dialog", "Средство поверки"))
        self.calibrator_edit.setText(_translate("Dialog", "Калибратор N4-25"))
        self.groupBox.setTitle(_translate("Dialog", "Поверяемый прибор"))
        self.label_2.setText(_translate("Dialog", "Система"))
        self.label_4.setText(_translate("Dialog", "Наименование"))
        self.label.setText(_translate("Dialog", "Класс"))
        self.label_5.setText(_translate("Dialog", "Изготовитель"))
        self.label_8.setText(_translate("Dialog", "Род тока"))
        self.signal_type_combobox.setItemText(0, _translate("Dialog", "I~"))
        self.signal_type_combobox.setItemText(1, _translate("Dialog", "U~"))
        self.signal_type_combobox.setItemText(2, _translate("Dialog", "I="))
        self.signal_type_combobox.setItemText(3, _translate("Dialog", "U="))
        self.system_combobox.setItemText(0, _translate("Dialog", "Магнитоэлектрическая"))
        self.system_combobox.setItemText(1, _translate("Dialog", "Электродинамическая"))
        self.system_combobox.setItemText(2, _translate("Dialog", "Электромагнитная"))
        self.add_point_button.setText(_translate("Dialog", "+"))
        self.remove_point_button.setText(_translate("Dialog", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Точки поверки"))
        item = self.marks_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Описание"))
        item = self.marks_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Метка"))
        item = self.marks_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Значение"))
        self.add_mark_button.setText(_translate("Dialog", "+"))
        self.remove_mark_button.setText(_translate("Dialog", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Пользовательские метки"))
        self.accept_button.setText(_translate("Dialog", "Сохранить"))
        self.reject_button.setText(_translate("Dialog", "Отмена"))
