# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/measure_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(1131, 566)
        font = QtGui.QFont()
        font.setPointSize(10)
        main_widget.setFont(font)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(main_widget)
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clb_list_combobox = QtWidgets.QComboBox(self.frame_3)
        self.clb_list_combobox.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.clb_list_combobox.setFont(font)
        self.clb_list_combobox.setObjectName("clb_list_combobox")
        self.horizontalLayout_3.addWidget(self.clb_list_combobox)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.clb_state_label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.clb_state_label.setFont(font)
        self.clb_state_label.setObjectName("clb_state_label")
        self.horizontalLayout_3.addWidget(self.clb_state_label)
        self.status_warning_label = QtWidgets.QLabel(self.frame_3)
        self.status_warning_label.setMinimumSize(QtCore.QSize(30, 0))
        self.status_warning_label.setText("")
        self.status_warning_label.setObjectName("status_warning_label")
        self.horizontalLayout_3.addWidget(self.status_warning_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.edit_parameters_button = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.edit_parameters_button.setFont(font)
        self.edit_parameters_button.setObjectName("edit_parameters_button")
        self.horizontalLayout_3.addWidget(self.edit_parameters_button)
        self.pause_button = QtWidgets.QPushButton(self.frame_3)
        self.pause_button.setEnabled(False)
        self.pause_button.setMinimumSize(QtCore.QSize(137, 0))
        self.pause_button.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pause_button.setFont(font)
        self.pause_button.setIconSize(QtCore.QSize(21, 21))
        self.pause_button.setCheckable(True)
        self.pause_button.setFlat(False)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout_3.addWidget(self.pause_button)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.splitter = QtWidgets.QSplitter(main_widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(5, 3, 5, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.frame)
        self.splitter_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter_2.setLineWidth(1)
        self.splitter_2.setMidLineWidth(5)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setOpaqueResize(True)
        self.splitter_2.setHandleWidth(5)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(-1, 11, -1, 11)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 2, 1, 1)
        self.rough_minus_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rough_minus_button.sizePolicy().hasHeightForWidth())
        self.rough_minus_button.setSizePolicy(sizePolicy)
        self.rough_minus_button.setMinimumSize(QtCore.QSize(0, 0))
        self.rough_minus_button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.rough_minus_button.setFont(font)
        self.rough_minus_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/minus2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rough_minus_button.setIcon(icon)
        self.rough_minus_button.setIconSize(QtCore.QSize(35, 35))
        self.rough_minus_button.setAutoRepeat(True)
        self.rough_minus_button.setAutoRepeatDelay(600)
        self.rough_minus_button.setAutoRepeatInterval(10)
        self.rough_minus_button.setObjectName("rough_minus_button")
        self.gridLayout_3.addWidget(self.rough_minus_button, 2, 0, 1, 1)
        self.fixed_plus_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixed_plus_button.sizePolicy().hasHeightForWidth())
        self.fixed_plus_button.setSizePolicy(sizePolicy)
        self.fixed_plus_button.setMinimumSize(QtCore.QSize(0, 0))
        self.fixed_plus_button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.fixed_plus_button.setFont(font)
        self.fixed_plus_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fixed_plus_button.setIcon(icon1)
        self.fixed_plus_button.setIconSize(QtCore.QSize(35, 35))
        self.fixed_plus_button.setAutoRepeat(True)
        self.fixed_plus_button.setAutoRepeatDelay(600)
        self.fixed_plus_button.setAutoRepeatInterval(10)
        self.fixed_plus_button.setObjectName("fixed_plus_button")
        self.gridLayout_3.addWidget(self.fixed_plus_button, 1, 3, 1, 1)
        self.common_plus_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.common_plus_button.sizePolicy().hasHeightForWidth())
        self.common_plus_button.setSizePolicy(sizePolicy)
        self.common_plus_button.setMinimumSize(QtCore.QSize(0, 0))
        self.common_plus_button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.common_plus_button.setFont(font)
        self.common_plus_button.setText("")
        self.common_plus_button.setIcon(icon1)
        self.common_plus_button.setIconSize(QtCore.QSize(35, 35))
        self.common_plus_button.setAutoRepeat(True)
        self.common_plus_button.setAutoRepeatDelay(600)
        self.common_plus_button.setAutoRepeatInterval(10)
        self.common_plus_button.setObjectName("common_plus_button")
        self.gridLayout_3.addWidget(self.common_plus_button, 1, 1, 1, 1)
        self.fixed_minus_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixed_minus_button.sizePolicy().hasHeightForWidth())
        self.fixed_minus_button.setSizePolicy(sizePolicy)
        self.fixed_minus_button.setMinimumSize(QtCore.QSize(0, 0))
        self.fixed_minus_button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.fixed_minus_button.setFont(font)
        self.fixed_minus_button.setText("")
        self.fixed_minus_button.setIcon(icon)
        self.fixed_minus_button.setIconSize(QtCore.QSize(35, 35))
        self.fixed_minus_button.setAutoRepeat(True)
        self.fixed_minus_button.setAutoRepeatDelay(600)
        self.fixed_minus_button.setAutoRepeatInterval(10)
        self.fixed_minus_button.setObjectName("fixed_minus_button")
        self.gridLayout_3.addWidget(self.fixed_minus_button, 2, 3, 1, 1)
        self.common_minus_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.common_minus_button.sizePolicy().hasHeightForWidth())
        self.common_minus_button.setSizePolicy(sizePolicy)
        self.common_minus_button.setMinimumSize(QtCore.QSize(0, 0))
        self.common_minus_button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.common_minus_button.setFont(font)
        self.common_minus_button.setText("")
        self.common_minus_button.setIcon(icon)
        self.common_minus_button.setIconSize(QtCore.QSize(35, 35))
        self.common_minus_button.setAutoRepeat(True)
        self.common_minus_button.setAutoRepeatDelay(600)
        self.common_minus_button.setAutoRepeatInterval(10)
        self.common_minus_button.setObjectName("common_minus_button")
        self.gridLayout_3.addWidget(self.common_minus_button, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(True)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.exact_minus_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exact_minus_button.sizePolicy().hasHeightForWidth())
        self.exact_minus_button.setSizePolicy(sizePolicy)
        self.exact_minus_button.setMinimumSize(QtCore.QSize(0, 0))
        self.exact_minus_button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.exact_minus_button.setFont(font)
        self.exact_minus_button.setText("")
        self.exact_minus_button.setIcon(icon)
        self.exact_minus_button.setIconSize(QtCore.QSize(35, 35))
        self.exact_minus_button.setAutoRepeat(True)
        self.exact_minus_button.setAutoRepeatDelay(600)
        self.exact_minus_button.setAutoRepeatInterval(10)
        self.exact_minus_button.setObjectName("exact_minus_button")
        self.gridLayout_3.addWidget(self.exact_minus_button, 2, 2, 1, 1)
        self.rough_plus_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rough_plus_button.sizePolicy().hasHeightForWidth())
        self.rough_plus_button.setSizePolicy(sizePolicy)
        self.rough_plus_button.setMinimumSize(QtCore.QSize(0, 0))
        self.rough_plus_button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.rough_plus_button.setFont(font)
        self.rough_plus_button.setText("")
        self.rough_plus_button.setIcon(icon1)
        self.rough_plus_button.setIconSize(QtCore.QSize(35, 35))
        self.rough_plus_button.setAutoRepeat(True)
        self.rough_plus_button.setAutoRepeatDelay(600)
        self.rough_plus_button.setAutoRepeatInterval(10)
        self.rough_plus_button.setObjectName("rough_plus_button")
        self.gridLayout_3.addWidget(self.rough_plus_button, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.label_2.setMouseTracking(False)
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.exact_plus_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exact_plus_button.sizePolicy().hasHeightForWidth())
        self.exact_plus_button.setSizePolicy(sizePolicy)
        self.exact_plus_button.setMinimumSize(QtCore.QSize(0, 0))
        self.exact_plus_button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.exact_plus_button.setFont(font)
        self.exact_plus_button.setText("")
        self.exact_plus_button.setIcon(icon1)
        self.exact_plus_button.setIconSize(QtCore.QSize(35, 35))
        self.exact_plus_button.setAutoRepeat(True)
        self.exact_plus_button.setAutoRepeatDelay(600)
        self.exact_plus_button.setAutoRepeatInterval(10)
        self.exact_plus_button.setObjectName("exact_plus_button")
        self.gridLayout_3.addWidget(self.exact_plus_button, 1, 2, 1, 1)
        self.fixed_step_combobox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixed_step_combobox.sizePolicy().hasHeightForWidth())
        self.fixed_step_combobox.setSizePolicy(sizePolicy)
        self.fixed_step_combobox.setMinimumSize(QtCore.QSize(115, 0))
        self.fixed_step_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(True)
        self.fixed_step_combobox.setFont(font)
        self.fixed_step_combobox.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.fixed_step_combobox.setEditable(False)
        self.fixed_step_combobox.setModelColumn(0)
        self.fixed_step_combobox.setObjectName("fixed_step_combobox")
        self.gridLayout_3.addWidget(self.fixed_step_combobox, 0, 3, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.apply_frequency_button = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_frequency_button.sizePolicy().hasHeightForWidth())
        self.apply_frequency_button.setSizePolicy(sizePolicy)
        self.apply_frequency_button.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.apply_frequency_button.setFont(font)
        self.apply_frequency_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.apply_frequency_button.setIcon(icon2)
        self.apply_frequency_button.setIconSize(QtCore.QSize(35, 35))
        self.apply_frequency_button.setObjectName("apply_frequency_button")
        self.gridLayout.addWidget(self.apply_frequency_button, 5, 1, 1, 1)
        self.apply_amplitude_button = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_amplitude_button.sizePolicy().hasHeightForWidth())
        self.apply_amplitude_button.setSizePolicy(sizePolicy)
        self.apply_amplitude_button.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.apply_amplitude_button.setFont(font)
        self.apply_amplitude_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.apply_amplitude_button.setIcon(icon3)
        self.apply_amplitude_button.setIconSize(QtCore.QSize(35, 35))
        self.apply_amplitude_button.setFlat(False)
        self.apply_amplitude_button.setObjectName("apply_amplitude_button")
        self.gridLayout.addWidget(self.apply_amplitude_button, 3, 1, 1, 1)
        self.frequency_edit = QEditCopyButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequency_edit.sizePolicy().hasHeightForWidth())
        self.frequency_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.frequency_edit.setFont(font)
        self.frequency_edit.setObjectName("frequency_edit")
        self.gridLayout.addWidget(self.frequency_edit, 5, 0, 1, 1)
        self.amplitude_edit = QEditCopyButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amplitude_edit.sizePolicy().hasHeightForWidth())
        self.amplitude_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.amplitude_edit.setFont(font)
        self.amplitude_edit.setStyleSheet("")
        self.amplitude_edit.setObjectName("amplitude_edit")
        self.gridLayout.addWidget(self.amplitude_edit, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.frame_7 = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.measure_table = QtWidgets.QTableView(self.frame_7)
        self.measure_table.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.measure_table.setFont(font)
        self.measure_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.measure_table.setStyleSheet("selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(170, 170, 255);")
        self.measure_table.setAlternatingRowColors(True)
        self.measure_table.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.measure_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.measure_table.setTextElideMode(QtCore.Qt.ElideLeft)
        self.measure_table.setSortingEnabled(False)
        self.measure_table.setObjectName("measure_table")
        self.gridLayout_2.addWidget(self.measure_table, 1, 0, 1, 1)
        self.cases_bar_layout = QtWidgets.QVBoxLayout()
        self.cases_bar_layout.setObjectName("cases_bar_layout")
        self.gridLayout_2.addLayout(self.cases_bar_layout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.save_point_button = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_point_button.sizePolicy().hasHeightForWidth())
        self.save_point_button.setSizePolicy(sizePolicy)
        self.save_point_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.save_point_button.setFont(font)
        self.save_point_button.setObjectName("save_point_button")
        self.verticalLayout.addWidget(self.save_point_button)
        self.go_to_point_button = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go_to_point_button.sizePolicy().hasHeightForWidth())
        self.go_to_point_button.setSizePolicy(sizePolicy)
        self.go_to_point_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.go_to_point_button.setFont(font)
        self.go_to_point_button.setObjectName("go_to_point_button")
        self.verticalLayout.addWidget(self.go_to_point_button)
        self.delete_point_button = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_point_button.sizePolicy().hasHeightForWidth())
        self.delete_point_button.setSizePolicy(sizePolicy)
        self.delete_point_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.delete_point_button.setFont(font)
        self.delete_point_button.setObjectName("delete_point_button")
        self.verticalLayout.addWidget(self.delete_point_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.start_stop_button = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_stop_button.sizePolicy().hasHeightForWidth())
        self.start_stop_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.start_stop_button.setFont(font)
        self.start_stop_button.setObjectName("start_stop_button")
        self.verticalLayout.addWidget(self.start_stop_button)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.splitter)

        self.retranslateUi(main_widget)
        self.fixed_step_combobox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(main_widget)
        main_widget.setTabOrder(self.clb_list_combobox, self.edit_parameters_button)
        main_widget.setTabOrder(self.edit_parameters_button, self.pause_button)
        main_widget.setTabOrder(self.pause_button, self.amplitude_edit)
        main_widget.setTabOrder(self.amplitude_edit, self.apply_amplitude_button)
        main_widget.setTabOrder(self.apply_amplitude_button, self.frequency_edit)
        main_widget.setTabOrder(self.frequency_edit, self.apply_frequency_button)
        main_widget.setTabOrder(self.apply_frequency_button, self.save_point_button)
        main_widget.setTabOrder(self.save_point_button, self.go_to_point_button)
        main_widget.setTabOrder(self.go_to_point_button, self.delete_point_button)
        main_widget.setTabOrder(self.delete_point_button, self.start_stop_button)

    def retranslateUi(self, main_widget):
        _translate = QtCore.QCoreApplication.translate
        main_widget.setWindowTitle(_translate("main_widget", "Form"))
        self.label_4.setText(_translate("main_widget", "Статус:"))
        self.clb_state_label.setText(_translate("main_widget", "Остановлен"))
        self.edit_parameters_button.setText(_translate("main_widget", "Изменить параметры измерения"))
        self.pause_button.setText(_translate("main_widget", "Возобновить"))
        self.groupBox.setTitle(_translate("main_widget", "Шаг"))
        self.label_3.setToolTip(_translate("main_widget", "Shift + колесо мыши"))
        self.label_3.setText(_translate("main_widget", "Точный"))
        self.label_8.setToolTip(_translate("main_widget", "Колесо мыши"))
        self.label_8.setText(_translate("main_widget", "Обычный"))
        self.label_2.setToolTip(_translate("main_widget", "Ctrl + колесо мыши"))
        self.label_2.setText(_translate("main_widget", "Грубый"))
        self.fixed_step_combobox.setToolTip(_translate("main_widget", "Ctrl + Shift + Колесо мыши"))
        self.frequency_edit.setText(_translate("main_widget", "0"))
        self.amplitude_edit.setText(_translate("main_widget", "0"))
        self.label_6.setText(_translate("main_widget", "Частота, Гц"))
        self.label_5.setText(_translate("main_widget", "Амплитуда"))
        self.save_point_button.setText(_translate("main_widget", "Сохранить\n"
"точку"))
        self.go_to_point_button.setText(_translate("main_widget", "Перейти\n"
"к точке"))
        self.delete_point_button.setText(_translate("main_widget", "Удалить\n"
"точку"))
        self.start_stop_button.setText(_translate("main_widget", "Начать\n"
"поверку"))
from custom_widgets.CustomLineEdit import QEditCopyButton
import icons_rc
