# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scale_limits_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(668, 236)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.limits_table = QtWidgets.QTableWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.limits_table.setFont(font)
        self.limits_table.setStyleSheet("selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(170, 170, 255);")
        self.limits_table.setAlternatingRowColors(True)
        self.limits_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.limits_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.limits_table.setObjectName("limits_table")
        self.limits_table.setColumnCount(5)
        self.limits_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.limits_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.limits_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.limits_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.limits_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.limits_table.setHorizontalHeaderItem(4, item)
        self.limits_table.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.limits_table)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_limit_button = QtWidgets.QPushButton(Dialog)
        self.add_limit_button.setMinimumSize(QtCore.QSize(35, 0))
        self.add_limit_button.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_limit_button.setFont(font)
        self.add_limit_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_limit_button.setIcon(icon)
        self.add_limit_button.setAutoDefault(False)
        self.add_limit_button.setObjectName("add_limit_button")
        self.verticalLayout_2.addWidget(self.add_limit_button)
        self.remove_limit_button = QtWidgets.QPushButton(Dialog)
        self.remove_limit_button.setMinimumSize(QtCore.QSize(35, 0))
        self.remove_limit_button.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.remove_limit_button.setFont(font)
        self.remove_limit_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_limit_button.setIcon(icon1)
        self.remove_limit_button.setAutoDefault(False)
        self.remove_limit_button.setObjectName("remove_limit_button")
        self.verticalLayout_2.addWidget(self.remove_limit_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.default_button = QtWidgets.QPushButton(Dialog)
        self.default_button.setEnabled(False)
        self.default_button.setDefault(True)
        self.default_button.setObjectName("default_button")
        self.horizontalLayout.addWidget(self.default_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.accept_button = QtWidgets.QPushButton(Dialog)
        self.accept_button.setAutoDefault(False)
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout.addWidget(self.accept_button)
        self.reject_button = QtWidgets.QPushButton(Dialog)
        self.reject_button.setAutoDefault(False)
        self.reject_button.setObjectName("reject_button")
        self.horizontalLayout.addWidget(self.reject_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.limits_table, self.accept_button)
        Dialog.setTabOrder(self.accept_button, self.reject_button)
        Dialog.setTabOrder(self.reject_button, self.default_button)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Изменение пределов шкалы"))
        item = self.limits_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Предел"))
        item = self.limits_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Класс\n"
"точности"))
        item = self.limits_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Тип\n"
"сигнала"))
        item = self.limits_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Частота, Гц"))
        item = self.limits_table.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "ID"))
        self.default_button.setText(_translate("Dialog", "default"))
        self.accept_button.setText(_translate("Dialog", "Принять"))
        self.reject_button.setText(_translate("Dialog", "Отмена"))
import icons
