# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/settings_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(558, 382)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layout = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layout.sizePolicy().hasHeightForWidth())
        self.layout.setSizePolicy(sizePolicy)
        self.layout.setMaximumSize(QtCore.QSize(150, 16777215))
        self.layout.setObjectName("layout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layout)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settings_menu_list = QtWidgets.QListWidget(self.layout)
        self.settings_menu_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.settings_menu_list.setProperty("isWrapping", False)
        self.settings_menu_list.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.settings_menu_list.setViewMode(QtWidgets.QListView.ListMode)
        self.settings_menu_list.setUniformItemSizes(False)
        self.settings_menu_list.setWordWrap(True)
        self.settings_menu_list.setSelectionRectVisible(False)
        self.settings_menu_list.setObjectName("settings_menu_list")
        item = QtWidgets.QListWidgetItem()
        self.settings_menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.settings_menu_list.addItem(item)
        self.verticalLayout_2.addWidget(self.settings_menu_list)
        self.horizontalLayout.addWidget(self.layout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settings_stackedwidget = QtWidgets.QStackedWidget(self.frame)
        self.settings_stackedwidget.setObjectName("settings_stackedwidget")
        self.marks_page = QtWidgets.QWidget()
        self.marks_page.setObjectName("marks_page")
        self.settings_stackedwidget.addWidget(self.marks_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.settings_stackedwidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.settings_stackedwidget)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.save_and_exit_button = QtWidgets.QPushButton(Dialog)
        self.save_and_exit_button.setObjectName("save_and_exit_button")
        self.horizontalLayout_2.addWidget(self.save_and_exit_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.save_button = QtWidgets.QPushButton(Dialog)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        self.settings_stackedwidget.setCurrentIndex(0)
        self.settings_menu_list.currentRowChanged['int'].connect(self.settings_stackedwidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки"))
        self.settings_menu_list.setSortingEnabled(False)
        __sortingEnabled = self.settings_menu_list.isSortingEnabled()
        self.settings_menu_list.setSortingEnabled(False)
        item = self.settings_menu_list.item(0)
        item.setText(_translate("Dialog", "Дополнительные параметры измерений"))
        item = self.settings_menu_list.item(1)
        item.setText(_translate("Dialog", "Параметры фиксированного шага"))
        self.settings_menu_list.setSortingEnabled(__sortingEnabled)
        self.save_and_exit_button.setText(_translate("Dialog", "Ок"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
        self.save_button.setText(_translate("Dialog", "Принять"))
