# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/source_mode_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(379, 282)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clb_list_combobox = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.clb_list_combobox.setFont(font)
        self.clb_list_combobox.setObjectName("clb_list_combobox")
        self.horizontalLayout_3.addWidget(self.clb_list_combobox)
        self.usb_state_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.usb_state_label.setFont(font)
        self.usb_state_label.setObjectName("usb_state_label")
        self.horizontalLayout_3.addWidget(self.usb_state_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.amplitude_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.amplitude_label.setFont(font)
        self.amplitude_label.setObjectName("amplitude_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.amplitude_label)
        self.frequency_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frequency_label.setFont(font)
        self.frequency_label.setObjectName("frequency_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.frequency_label)
        self.amplitude_edit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.amplitude_edit.setFont(font)
        self.amplitude_edit.setMaxLength(20)
        self.amplitude_edit.setFrame(True)
        self.amplitude_edit.setClearButtonEnabled(True)
        self.amplitude_edit.setObjectName("amplitude_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.amplitude_edit)
        self.frequency_spinbox = QtWidgets.QDoubleSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frequency_spinbox.setFont(font)
        self.frequency_spinbox.setDecimals(11)
        self.frequency_spinbox.setMinimum(40.0)
        self.frequency_spinbox.setMaximum(2000.0)
        self.frequency_spinbox.setObjectName("frequency_spinbox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frequency_spinbox)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.aci_radio = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.aci_radio.setFont(font)
        self.aci_radio.setChecked(True)
        self.aci_radio.setObjectName("aci_radio")
        self.signal_group = QtWidgets.QButtonGroup(Form)
        self.signal_group.setObjectName("signal_group")
        self.signal_group.addButton(self.aci_radio)
        self.horizontalLayout_2.addWidget(self.aci_radio)
        self.acv_radio = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.acv_radio.setFont(font)
        self.acv_radio.setChecked(False)
        self.acv_radio.setObjectName("acv_radio")
        self.signal_group.addButton(self.acv_radio)
        self.horizontalLayout_2.addWidget(self.acv_radio)
        self.dcv_radio = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dcv_radio.setFont(font)
        self.dcv_radio.setObjectName("dcv_radio")
        self.signal_group.addButton(self.dcv_radio)
        self.horizontalLayout_2.addWidget(self.dcv_radio)
        self.dci_radio = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dci_radio.setFont(font)
        self.dci_radio.setObjectName("dci_radio")
        self.signal_group.addButton(self.dci_radio)
        self.horizontalLayout_2.addWidget(self.dci_radio)
        self.polarity_button = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.polarity_button.setFont(font)
        self.polarity_button.setCheckable(True)
        self.polarity_button.setObjectName("polarity_button")
        self.horizontalLayout_2.addWidget(self.polarity_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.source_mode_radio = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.source_mode_radio.setFont(font)
        self.source_mode_radio.setChecked(True)
        self.source_mode_radio.setObjectName("source_mode_radio")
        self.mode_group = QtWidgets.QButtonGroup(Form)
        self.mode_group.setObjectName("mode_group")
        self.mode_group.addButton(self.source_mode_radio)
        self.horizontalLayout_5.addWidget(self.source_mode_radio)
        self.fixed_mode_radio = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.fixed_mode_radio.setFont(font)
        self.fixed_mode_radio.setObjectName("fixed_mode_radio")
        self.mode_group.addButton(self.fixed_mode_radio)
        self.horizontalLayout_5.addWidget(self.fixed_mode_radio)
        self.detuning_radio = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.detuning_radio.setFont(font)
        self.detuning_radio.setObjectName("detuning_radio")
        self.mode_group.addButton(self.detuning_radio)
        self.horizontalLayout_5.addWidget(self.detuning_radio)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.enable_button = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.enable_button.setFont(font)
        self.enable_button.setCheckable(True)
        self.enable_button.setObjectName("enable_button")
        self.verticalLayout_2.addWidget(self.enable_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.usb_state_label.setText(_translate("Form", "Отключено"))
        self.amplitude_label.setText(_translate("Form", "Амплитуда"))
        self.frequency_label.setText(_translate("Form", "Частота"))
        self.amplitude_edit.setText(_translate("Form", "0"))
        self.aci_radio.setText(_translate("Form", "~I"))
        self.acv_radio.setText(_translate("Form", "~U"))
        self.dcv_radio.setText(_translate("Form", "=U"))
        self.dci_radio.setText(_translate("Form", "=I"))
        self.polarity_button.setText(_translate("Form", "+"))
        self.source_mode_radio.setText(_translate("Form", "Источник"))
        self.fixed_mode_radio.setText(_translate("Form", "Фиксир."))
        self.detuning_radio.setText(_translate("Form", "Расстройка"))
        self.enable_button.setText(_translate("Form", "Enable"))
