# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startform.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start_dialog(object):
    def setupUi(self, start_dialog):
        start_dialog.setObjectName("start_dialog")
        start_dialog.resize(1027, 458)
        font = QtGui.QFont()
        font.setPointSize(13)
        start_dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(start_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(start_dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.create_protocol_button = QtWidgets.QToolButton(start_dialog)
        self.create_protocol_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_protocol_button.sizePolicy().hasHeightForWidth())
        self.create_protocol_button.setSizePolicy(sizePolicy)
        self.create_protocol_button.setMinimumSize(QtCore.QSize(100, 0))
        self.create_protocol_button.setAutoRaise(True)
        self.create_protocol_button.setArrowType(QtCore.Qt.NoArrow)
        self.create_protocol_button.setObjectName("create_protocol_button")
        self.horizontalLayout.addWidget(self.create_protocol_button)
        self.line_2 = QtWidgets.QFrame(start_dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.source_mode_button = QtWidgets.QToolButton(start_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_mode_button.sizePolicy().hasHeightForWidth())
        self.source_mode_button.setSizePolicy(sizePolicy)
        self.source_mode_button.setMinimumSize(QtCore.QSize(100, 0))
        self.source_mode_button.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.source_mode_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.source_mode_button.setAutoRaise(True)
        self.source_mode_button.setObjectName("source_mode_button")
        self.horizontalLayout.addWidget(self.source_mode_button)
        self.line_3 = QtWidgets.QFrame(start_dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.no_template_mode_button = QtWidgets.QToolButton(start_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.no_template_mode_button.sizePolicy().hasHeightForWidth())
        self.no_template_mode_button.setSizePolicy(sizePolicy)
        self.no_template_mode_button.setMinimumSize(QtCore.QSize(100, 0))
        self.no_template_mode_button.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.no_template_mode_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.no_template_mode_button.setAutoRaise(True)
        self.no_template_mode_button.setObjectName("no_template_mode_button")
        self.horizontalLayout.addWidget(self.no_template_mode_button)
        self.line_4 = QtWidgets.QFrame(start_dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.template_mode_button = QtWidgets.QToolButton(start_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.template_mode_button.sizePolicy().hasHeightForWidth())
        self.template_mode_button.setSizePolicy(sizePolicy)
        self.template_mode_button.setMinimumSize(QtCore.QSize(100, 0))
        self.template_mode_button.setAutoRaise(True)
        self.template_mode_button.setArrowType(QtCore.Qt.NoArrow)
        self.template_mode_button.setObjectName("template_mode_button")
        self.horizontalLayout.addWidget(self.template_mode_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.measures_table = QtWidgets.QTableView(start_dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.measures_table.setFont(font)
        self.measures_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.measures_table.setStyleSheet("selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(170, 170, 255);")
        self.measures_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.measures_table.setDragEnabled(False)
        self.measures_table.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.measures_table.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.measures_table.setAlternatingRowColors(True)
        self.measures_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.measures_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.measures_table.setSortingEnabled(True)
        self.measures_table.setWordWrap(True)
        self.measures_table.setObjectName("measures_table")
        self.measures_table.horizontalHeader().setSortIndicatorShown(True)
        self.measures_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.measures_table)

        self.retranslateUi(start_dialog)
        QtCore.QMetaObject.connectSlotsByName(start_dialog)
        start_dialog.setTabOrder(self.create_protocol_button, self.source_mode_button)
        start_dialog.setTabOrder(self.source_mode_button, self.no_template_mode_button)
        start_dialog.setTabOrder(self.no_template_mode_button, self.template_mode_button)
        start_dialog.setTabOrder(self.template_mode_button, self.measures_table)

    def retranslateUi(self, start_dialog):
        _translate = QtCore.QCoreApplication.translate
        start_dialog.setWindowTitle(_translate("start_dialog", "Form"))
        self.label.setText(_translate("start_dialog", "Последние измерения"))
        self.create_protocol_button.setText(_translate("start_dialog", "Создать\n"
"отчет"))
        self.source_mode_button.setText(_translate("start_dialog", "Режим\n"
"источника"))
        self.no_template_mode_button.setText(_translate("start_dialog", "Быстрая\n"
"поверка"))
        self.template_mode_button.setText(_translate("start_dialog", "Шаблоны\n"
"поверки"))
