# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/template_list_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(310, 398)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filter_template_edit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.filter_template_edit.setFont(font)
        self.filter_template_edit.setObjectName("filter_template_edit")
        self.horizontalLayout_2.addWidget(self.filter_template_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.add_template_button = QtWidgets.QPushButton(Dialog)
        self.add_template_button.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.add_template_button.setFont(font)
        self.add_template_button.setObjectName("add_template_button")
        self.horizontalLayout_2.addWidget(self.add_template_button)
        self.edit_template_button = QtWidgets.QPushButton(Dialog)
        self.edit_template_button.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.edit_template_button.setFont(font)
        self.edit_template_button.setObjectName("edit_template_button")
        self.horizontalLayout_2.addWidget(self.edit_template_button)
        self.delete_template_button = QtWidgets.QPushButton(Dialog)
        self.delete_template_button.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.delete_template_button.setFont(font)
        self.delete_template_button.setObjectName("delete_template_button")
        self.horizontalLayout_2.addWidget(self.delete_template_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.template_list = QtWidgets.QListWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.template_list.setFont(font)
        self.template_list.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.template_list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.template_list.setAlternatingRowColors(True)
        self.template_list.setMovement(QtWidgets.QListView.Free)
        self.template_list.setFlow(QtWidgets.QListView.TopToBottom)
        self.template_list.setProperty("isWrapping", False)
        self.template_list.setResizeMode(QtWidgets.QListView.Fixed)
        self.template_list.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.template_list.setViewMode(QtWidgets.QListView.ListMode)
        self.template_list.setModelColumn(0)
        self.template_list.setUniformItemSizes(False)
        self.template_list.setSelectionRectVisible(False)
        self.template_list.setObjectName("template_list")
        self.verticalLayout.addWidget(self.template_list)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.accept_button = QtWidgets.QPushButton(Dialog)
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout.addWidget(self.accept_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Шаблоны поверки"))
        self.filter_template_edit.setPlaceholderText(_translate("Dialog", "Поиск..."))
        self.add_template_button.setText(_translate("Dialog", "+"))
        self.edit_template_button.setText(_translate("Dialog", "..."))
        self.delete_template_button.setText(_translate("Dialog", "-"))
        self.template_list.setSortingEnabled(True)
        self.accept_button.setText(_translate("Dialog", "Выбрать"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
